"""Realistic Canadian portfolio data for Wealthgate."""

CLIENTS = {
    "CLI-001": {
        "name": "Alex Morrison",
        "accounts": {
            "TFSA-001": {
                "type": "TFSA",
                "contribution_room": 7000.00,
                "holdings": [
                    {"symbol": "XEQT.TO", "units": 312, "avg_cost": 28.45},
                    {"symbol": "VFV.TO", "units": 150, "avg_cost": 108.20},
                    {"symbol": "XIC.TO", "units": 200, "avg_cost": 33.10},
                    {"symbol": "ZAG.TO", "units": 180, "avg_cost": 14.85},
                ],
                "cash": 1245.30,
            },
            "RRSP-001": {
                "type": "RRSP",
                "deduction_limit": 12500.00,
                "holdings": [
                    {"symbol": "VEQT.TO", "units": 250, "avg_cost": 35.60},
                    {"symbol": "XBB.TO", "units": 300, "avg_cost": 28.90},
                    {"symbol": "VDY.TO", "units": 175, "avg_cost": 42.30},
                ],
                "cash": 890.00,
            },
            "NON-REG-001": {
                "type": "Non-Registered",
                "holdings": [
                    {"symbol": "SHOP.TO", "units": 25, "avg_cost": 95.40},
                    {"symbol": "RY.TO", "units": 50, "avg_cost": 145.00},
                    {"symbol": "ENB.TO", "units": 100, "avg_cost": 52.80},
                    {"symbol": "TD.TO", "units": 40, "avg_cost": 85.20},
                ],
                "cash": 2340.00,
            },
        },
    }
}

INVESTMENT_UNIVERSE = [
    {"symbol": "XEQT.TO", "name": "iShares Core Equity ETF Portfolio", "type": "ETF", "mer": 0.20, "category": "All-in-one Equity", "description": "Broadly diversified global equity portfolio"},
    {"symbol": "VEQT.TO", "name": "Vanguard All-Equity ETF Portfolio", "type": "ETF", "mer": 0.24, "category": "All-in-one Equity", "description": "100% equity allocation across global markets"},
    {"symbol": "XGRO.TO", "name": "iShares Core Growth ETF Portfolio", "type": "ETF", "mer": 0.20, "category": "All-in-one Balanced", "description": "80/20 equity/bond growth allocation"},
    {"symbol": "VGRO.TO", "name": "Vanguard Growth ETF Portfolio", "type": "ETF", "mer": 0.24, "category": "All-in-one Balanced", "description": "80/20 equity/bond growth portfolio"},
    {"symbol": "VFV.TO", "name": "Vanguard S&P 500 Index ETF", "type": "ETF", "mer": 0.09, "category": "US Equity", "description": "Tracks S&P 500 in CAD"},
    {"symbol": "XIC.TO", "name": "iShares Core S&P/TSX Capped Composite", "type": "ETF", "mer": 0.06, "category": "Canadian Equity", "description": "Broad Canadian equity market exposure"},
    {"symbol": "XUU.TO", "name": "iShares Core S&P US Total Market", "type": "ETF", "mer": 0.07, "category": "US Equity", "description": "Total US stock market exposure"},
    {"symbol": "ZAG.TO", "name": "BMO Aggregate Bond Index ETF", "type": "ETF", "mer": 0.09, "category": "Fixed Income", "description": "Canadian investment-grade bond exposure"},
    {"symbol": "XBB.TO", "name": "iShares Core Canadian Universe Bond", "type": "ETF", "mer": 0.10, "category": "Fixed Income", "description": "Broad Canadian bond market index"},
    {"symbol": "VDY.TO", "name": "Vanguard FTSE Canadian High Dividend", "type": "ETF", "mer": 0.22, "category": "Canadian Dividend", "description": "High-yield Canadian dividend stocks"},
    {"symbol": "SHOP.TO", "name": "Shopify Inc.", "type": "Stock", "category": "Technology", "description": "Canadian e-commerce platform"},
    {"symbol": "RY.TO", "name": "Royal Bank of Canada", "type": "Stock", "category": "Financial Services", "description": "Canada's largest bank by market cap"},
    {"symbol": "TD.TO", "name": "Toronto-Dominion Bank", "type": "Stock", "category": "Financial Services", "description": "Major Canadian bank with US operations"},
    {"symbol": "ENB.TO", "name": "Enbridge Inc.", "type": "Stock", "category": "Energy", "description": "North American energy infrastructure"},
    {"symbol": "CNR.TO", "name": "Canadian National Railway", "type": "Stock", "category": "Industrials", "description": "Transcontinental railway network"},
    {"symbol": "BAM.TO", "name": "Brookfield Asset Management", "type": "Stock", "category": "Financial Services", "description": "Global alternative asset manager"},
    {"symbol": "CSU.TO", "name": "Constellation Software", "type": "Stock", "category": "Technology", "description": "Vertical market software conglomerate"},
    {"symbol": "BN.TO", "name": "Brookfield Corporation", "type": "Stock", "category": "Financial Services", "description": "Global alternative investment company"},
]

# Map symbols to fallback prices for when yfinance is unavailable
MOCK_PRICES = {
    "XEQT.TO": 31.20,
    "VEQT.TO": 37.80,
    "XGRO.TO": 27.50,
    "VGRO.TO": 33.40,
    "VFV.TO": 112.50,
    "XIC.TO": 35.20,
    "XUU.TO": 38.90,
    "ZAG.TO": 14.50,
    "XBB.TO": 28.10,
    "VDY.TO": 44.80,
    "SHOP.TO": 105.30,
    "RY.TO": 158.40,
    "TD.TO": 82.50,
    "ENB.TO": 55.60,
    "CNR.TO": 162.30,
    "BAM.TO": 68.90,
    "CSU.TO": 4120.00,
    "BN.TO": 72.40,
}

SEED_PROPOSALS = [
    {
        "id": "WS-2026-00001",
        "agent_id": "claude-financial-advisor",
        "agent_name": "Claude (Financial Advisor)",
        "account_id": "TFSA-001",
        "type": "trade",
        "action": "buy",
        "symbol": "XEQT.TO",
        "units": 50,
        "estimated_value": 1560.00,
        "tier": 2,
        "reasoning": "Client's TFSA has $1,245 in cash and $7,000 in new contribution room. XEQT.TO provides globally diversified equity exposure at 0.20% MER, aligning with the portfolio's growth-oriented allocation. Buying 50 units at ~$31.20 deploys available cash while maintaining liquidity buffer.",
        "status": "pending",
        "created_at": "2026-02-24T10:15:00Z",
    },
    {
        "id": "WS-2026-00002",
        "agent_id": "chatgpt-portfolio-manager",
        "agent_name": "ChatGPT (Portfolio Rebalancer)",
        "account_id": "RRSP-001",
        "type": "rebalance",
        "action": "rebalance",
        "trades": [
            {"action": "sell", "symbol": "XBB.TO", "units": 100, "est_value": 2890.00},
            {"action": "buy", "symbol": "VEQT.TO", "units": 80, "est_value": 2848.00},
        ],
        "estimated_value": 5738.00,
        "tier": 3,
        "reasoning": "RRSP-001 is currently 35% bonds (XBB.TO) which is overweight for a 32-year-old with 30+ years to retirement. Proposing shift from bonds to all-equity (VEQT.TO) to increase long-term growth potential. This moves bond allocation from 35% to 23%, closer to age-appropriate target of 20%.",
        "status": "approved",
        "approved_by": "Almir Moura",
        "approved_at": "2026-02-24T10:45:00Z",
        "created_at": "2026-02-24T10:30:00Z",
    },
    {
        "id": "WS-2026-00003",
        "agent_id": "claude-tax-optimizer",
        "agent_name": "Claude (Tax Optimizer)",
        "account_id": "NON-REG-001",
        "type": "trade",
        "action": "sell",
        "symbol": "TD.TO",
        "units": 40,
        "estimated_value": 3408.00,
        "tier": 2,
        "reasoning": "Tax-loss harvesting opportunity: TD.TO is currently trading at $85.20 (avg cost $85.20) — essentially flat. However, given recent bank sector weakness, selling now and buying RY.TO (similar sector exposure, better momentum) would realize a small capital loss for 2026 tax purposes while maintaining Canadian financial sector allocation. No superficial loss concern as TD→RY is not substantially identical.",
        "status": "pending",
        "created_at": "2026-02-24T11:00:00Z",
    },
    {
        "id": "WS-2026-00004",
        "agent_id": "claude-financial-advisor",
        "agent_name": "Claude (Financial Advisor)",
        "account_id": "TFSA-001",
        "type": "trade",
        "action": "sell",
        "symbol": "VFV.TO",
        "units": 150,
        "estimated_value": 16230.00,
        "tier": 3,
        "reasoning": "ALERT: Significant market downturn detected. S&P 500 has dropped 12% in the past week. VFV.TO (S&P 500 tracker) is the most exposed position. However, I am flagging this for human review rather than recommending action. Historical analysis shows that selling during >10% drawdowns has negative expected value in 73% of cases over a 5-year horizon. The human reviewer should consider: (1) client's upcoming cash needs, (2) personal risk tolerance not captured in my data, (3) whether this is a systemic event or sector-specific.",
        "status": "rejected",
        "rejected_by": "Almir Moura",
        "rejection_reason": "Agree with agent's own caution. Client has 30+ year horizon. Holding through volatility is the right call. Good flag by the agent.",
        "created_at": "2026-02-24T09:00:00Z",
    },
    {
        "id": "WS-2026-00005",
        "agent_id": "chatgpt-portfolio-manager",
        "agent_name": "ChatGPT (Portfolio Rebalancer)",
        "account_id": "TFSA-001",
        "type": "withdrawal",
        "action": "withdraw",
        "estimated_value": 5000.00,
        "tier": 4,
        "reasoning": "Client requested transfer of $5,000 from TFSA to chequing account.",
        "status": "blocked",
        "block_reason": "Tier 4: Withdrawal operations are not available to AI agents. This action requires direct human authorisation through the Wealthsimple app.",
        "created_at": "2026-02-24T11:30:00Z",
    },
]


# ---------------------------------------------------------------------------
# Agent Transcript — Narrative replay of MCP sessions for demo page
# ---------------------------------------------------------------------------

TRANSCRIPT_ENTRIES = [
    # ── Act 1 ─────────────────────────────────────────────────────────────
    {
        "type": "act",
        "act_number": 1,
        "title": "The Discovery",
        "agent_id": "claude-financial-advisor",
        "agent_label": "Claude (Financial Advisor)",
        "description": "Agent connects, reads the portfolio, and spots an opportunity to deploy idle cash.",
        "highlight": False,
    },
    {
        "type": "step",
        "timestamp": "2026-02-24T10:14:30Z",
        "agent_id": "claude-financial-advisor",
        "agent_label": "Claude (Financial Advisor)",
        "tool": "get_portfolio",
        "tool_display": 'get_portfolio(account_id="TFSA-001")',
        "tier": 0,
        "decision": "auto_approved",
        "narrative": "Agent reads Alex Morrison's TFSA. Discovers $1,245 in idle cash and 4 holdings worth ~$25,400. Contribution room: $7,000.",
        "detail": "Read-only operation. Tier 0 — always allowed, no authorisation gate.",
        "request_json": {
            "jsonrpc": "2.0",
            "method": "tools/call",
            "params": {
                "name": "get_portfolio",
                "arguments": {"account_id": "TFSA-001", "agent_id": "claude-financial-advisor"},
            },
        },
        "response_json": {
            "account_id": "TFSA-001",
            "account_type": "TFSA",
            "cash_available": 1245.30,
            "total_value": 25482.30,
            "holdings": [
                {"symbol": "XEQT.TO", "units": 312, "weight": "38.2%"},
                {"symbol": "VFV.TO", "units": 150, "weight": "26.3%"},
                {"symbol": "XIC.TO", "units": 200, "weight": "13.8%"},
                {"symbol": "ZAG.TO", "units": 180, "weight": "5.1%"},
            ],
        },
        "proposal_id": None,
        "highlight": False,
    },
    {
        "type": "step",
        "timestamp": "2026-02-24T10:15:10Z",
        "agent_id": "claude-financial-advisor",
        "agent_label": "Claude (Financial Advisor)",
        "tool": "search_investments",
        "tool_display": 'search_investments(query="equity ETF")',
        "tier": 0,
        "decision": "auto_approved",
        "narrative": "Agent searches for equity ETFs to deploy the idle cash. Finds 6 matching instruments including XEQT.TO at $31.20 with 0.20% MER.",
        "detail": "Read-only search. Tier 0.",
        "request_json": {
            "jsonrpc": "2.0",
            "method": "tools/call",
            "params": {
                "name": "search_investments",
                "arguments": {"query": "equity ETF", "agent_id": "claude-financial-advisor"},
            },
        },
        "response_json": {
            "results": 6,
            "top_match": {"symbol": "XEQT.TO", "name": "iShares Core Equity ETF Portfolio", "price": 31.20, "mer": "0.20%"},
        },
        "proposal_id": None,
        "highlight": False,
    },
    {
        "type": "step",
        "timestamp": "2026-02-24T10:16:00Z",
        "agent_id": "claude-financial-advisor",
        "agent_label": "Claude (Financial Advisor)",
        "tool": "propose_trade",
        "tool_display": 'propose_trade(account_id="TFSA-001", action="buy", symbol="XEQT.TO", units=50)',
        "tier": 2,
        "decision": "pending_human_approval",
        "narrative": "Agent proposes buying 50 XEQT.TO for $1,560. At $31.20/unit, this deploys idle cash while keeping a small liquidity buffer. Value exceeds $100 — triggers Tier 2 human approval.",
        "detail": "Estimated value $1,560 > $100 threshold. Proposal enters the dashboard queue for human review.",
        "request_json": {
            "jsonrpc": "2.0",
            "method": "tools/call",
            "params": {
                "name": "propose_trade",
                "arguments": {
                    "account_id": "TFSA-001",
                    "action": "buy",
                    "symbol": "XEQT.TO",
                    "units": 50,
                    "reasoning": "Client's TFSA has $1,245 in cash and $7,000 in new contribution room. XEQT.TO provides globally diversified equity exposure at 0.20% MER.",
                },
            },
        },
        "response_json": {
            "proposal_id": "WS-2026-00001",
            "status": "pending_human_approval",
            "authorization_tier": 2,
            "estimated_value": 1560.00,
            "requires_human_approval": True,
            "message": "Trade proposal created. Estimated value $1,560.00. Requires human approval.",
        },
        "proposal_id": "WS-2026-00001",
        "highlight": False,
    },

    # ── Act 2 ─────────────────────────────────────────────────────────────
    {
        "type": "act",
        "act_number": 2,
        "title": "The Rebalancer",
        "agent_id": "chatgpt-portfolio-manager",
        "agent_label": "ChatGPT (Portfolio Rebalancer)",
        "description": "A second agent connects and proposes a multi-trade portfolio rebalance.",
        "highlight": False,
    },
    {
        "type": "step",
        "timestamp": "2026-02-24T10:28:00Z",
        "agent_id": "chatgpt-portfolio-manager",
        "agent_label": "ChatGPT (Portfolio Rebalancer)",
        "tool": "get_portfolio",
        "tool_display": 'get_portfolio(account_id="RRSP-001")',
        "tier": 0,
        "decision": "auto_approved",
        "narrative": "Second agent reads the RRSP portfolio. Finds 35% bonds (XBB.TO) — overweight for a 32-year-old with 30+ years to retirement.",
        "detail": "Read-only. Tier 0.",
        "request_json": {
            "jsonrpc": "2.0",
            "method": "tools/call",
            "params": {"name": "get_portfolio", "arguments": {"account_id": "RRSP-001"}},
        },
        "response_json": {
            "account_id": "RRSP-001",
            "account_type": "RRSP",
            "total_value": 19203.00,
            "holdings": [
                {"symbol": "VEQT.TO", "units": 250, "weight": "46.4%"},
                {"symbol": "XBB.TO", "units": 300, "weight": "35.1%"},
                {"symbol": "VDY.TO", "units": 175, "weight": "14.0%"},
            ],
        },
        "proposal_id": None,
        "highlight": False,
    },
    {
        "type": "step",
        "timestamp": "2026-02-24T10:30:00Z",
        "agent_id": "chatgpt-portfolio-manager",
        "agent_label": "ChatGPT (Portfolio Rebalancer)",
        "tool": "propose_rebalance",
        "tool_display": 'propose_rebalance(account_id="RRSP-001", target_allocation={...})',
        "tier": 3,
        "decision": "pending_with_cooling",
        "narrative": "Agent proposes selling 100 XBB.TO ($2,890) and buying 80 VEQT.TO ($2,848). Total value $5,738 exceeds $5,000 — triggers Tier 3 with a 15-minute mandatory cooling period.",
        "detail": "Estimated value $5,738 > $5,000 threshold. Human cannot approve for 15 minutes — a forced pause on large decisions.",
        "request_json": {
            "jsonrpc": "2.0",
            "method": "tools/call",
            "params": {
                "name": "propose_rebalance",
                "arguments": {
                    "account_id": "RRSP-001",
                    "target_allocation": {"VEQT.TO": 60, "XBB.TO": 20, "VDY.TO": 20},
                    "reasoning": "RRSP-001 is currently 35% bonds which is overweight for a 32-year-old with a 30+ year investment horizon.",
                },
            },
        },
        "response_json": {
            "proposal_id": "WS-2026-00002",
            "status": "pending_with_cooling",
            "authorization_tier": 3,
            "trades": [
                {"action": "sell", "symbol": "XBB.TO", "units": 100, "est_value": 2890.00},
                {"action": "buy", "symbol": "VEQT.TO", "units": 80, "est_value": 2848.00},
            ],
            "total_value": 5738.00,
            "cooling_expires_at": "2026-02-24T10:45:00Z",
        },
        "proposal_id": "WS-2026-00002",
        "highlight": False,
    },
    {
        "type": "step",
        "timestamp": "2026-02-24T10:45:00Z",
        "agent_id": "human",
        "agent_label": "Almir Moura",
        "tool": "approve_proposal",
        "tool_display": "Dashboard Action: Approve WS-2026-00002",
        "tier": None,
        "decision": "approved",
        "narrative": "After the 15-minute cooling period expires, Almir Moura approves the rebalance. The time-gate ensured no impulsive decisions on a $5,738 multi-trade.",
        "detail": "Human approval via the dashboard. Cooling period expired. Rebalance approved.",
        "request_json": None,
        "response_json": None,
        "proposal_id": "WS-2026-00002",
        "highlight": False,
    },

    # ── Act 3 ─────────────────────────────────────────────────────────────
    {
        "type": "act",
        "act_number": 3,
        "title": "The Tax Optimiser",
        "agent_id": "claude-tax-optimizer",
        "agent_label": "Claude (Tax Optimiser)",
        "description": "A specialised agent identifies a tax-loss harvesting opportunity in the taxable account.",
        "highlight": False,
    },
    {
        "type": "step",
        "timestamp": "2026-02-24T10:58:00Z",
        "agent_id": "claude-tax-optimizer",
        "agent_label": "Claude (Tax Optimiser)",
        "tool": "get_portfolio",
        "tool_display": 'get_portfolio(account_id="NON-REG-001")',
        "tier": 0,
        "decision": "auto_approved",
        "narrative": "Tax optimiser reads the non-registered (taxable) account. Identifies TD.TO trading near cost basis — a tax-loss harvesting candidate.",
        "detail": "Read-only. Tier 0.",
        "request_json": {
            "jsonrpc": "2.0",
            "method": "tools/call",
            "params": {"name": "get_portfolio", "arguments": {"account_id": "NON-REG-001"}},
        },
        "response_json": {
            "account_id": "NON-REG-001",
            "account_type": "Non-Registered",
            "holdings": [
                {"symbol": "SHOP.TO", "units": 25, "gain_loss_pct": "+10.4%"},
                {"symbol": "RY.TO", "units": 50, "gain_loss_pct": "+9.2%"},
                {"symbol": "ENB.TO", "units": 100, "gain_loss_pct": "+5.3%"},
                {"symbol": "TD.TO", "units": 40, "gain_loss_pct": "-3.2%"},
            ],
        },
        "proposal_id": None,
        "highlight": False,
    },
    {
        "type": "step",
        "timestamp": "2026-02-24T11:00:00Z",
        "agent_id": "claude-tax-optimizer",
        "agent_label": "Claude (Tax Optimiser)",
        "tool": "propose_trade",
        "tool_display": 'propose_trade(account_id="NON-REG-001", action="sell", symbol="TD.TO", units=40)',
        "tier": 2,
        "decision": "pending_human_approval",
        "narrative": "Agent proposes selling 40 TD.TO for $3,408 to realise a capital loss for 2026 taxes. Plans to replace with RY.TO for similar sector exposure — no superficial loss concern. Smart tax optimisation.",
        "detail": "Estimated value $3,408. Tier 2 — requires human approval.",
        "request_json": {
            "jsonrpc": "2.0",
            "method": "tools/call",
            "params": {
                "name": "propose_trade",
                "arguments": {
                    "account_id": "NON-REG-001",
                    "action": "sell",
                    "symbol": "TD.TO",
                    "units": 40,
                    "reasoning": "Tax-loss harvesting opportunity: TD.TO is currently trading at $85.20 (avg cost $85.20) — essentially flat. However, given recent bank sector headwinds, realising this loss now offsets $3,408 in capital gains elsewhere in 2026.",
                },
            },
        },
        "response_json": {
            "proposal_id": "WS-2026-00003",
            "status": "pending_human_approval",
            "authorization_tier": 2,
            "estimated_value": 3408.00,
        },
        "proposal_id": "WS-2026-00003",
        "highlight": False,
    },

    # ── Act 4 — THE THESIS MOMENT ─────────────────────────────────────────
    {
        "type": "act",
        "act_number": 4,
        "title": "The Thesis Moment",
        "agent_id": "claude-financial-advisor",
        "agent_label": "Claude (Financial Advisor)",
        "description": "The agent detects a market downturn — and chooses NOT to recommend panic-selling. This is responsible AI.",
        "highlight": True,
    },
    {
        "type": "step",
        "timestamp": "2026-02-24T09:00:00Z",
        "agent_id": "claude-financial-advisor",
        "agent_label": "Claude (Financial Advisor)",
        "tool": "propose_trade",
        "tool_display": 'propose_trade(account_id="TFSA-001", action="sell", symbol="VFV.TO", units=150)',
        "tier": 3,
        "decision": "pending_with_cooling",
        "narrative": "S&P 500 dropped 12% this week. VFV.TO is the most exposed holding. The agent flags the situation for human review — but its reasoning explicitly argues against panic-selling. It cites that selling during >10% drawdowns has negative expected value in 73% of cases over a 5-year horizon.",
        "detail": "Value $16,230. Tier 3 with cooling. The real story is in the reasoning — the agent defers to human judgement.",
        "request_json": {
            "jsonrpc": "2.0",
            "method": "tools/call",
            "params": {
                "name": "propose_trade",
                "arguments": {
                    "account_id": "TFSA-001",
                    "action": "sell",
                    "symbol": "VFV.TO",
                    "units": 150,
                    "reasoning": "ALERT: Significant market downturn detected. S&P 500 has dropped 12% in the past week. However, I am flagging this for human review rather than recommending action. Historical analysis shows that selling during >10% drawdowns has negative expected value 73% of the time over a 5-year horizon. I recommend human review because factors beyond my analysis include: (1) client's upcoming cash needs, (2) personal risk tolerance changes, (3) whether this is a systemic vs. sector-specific event.",
                },
            },
        },
        "response_json": {
            "proposal_id": "WS-2026-00004",
            "status": "pending_with_cooling",
            "authorization_tier": 3,
            "estimated_value": 16230.00,
            "requires_human_approval": True,
            "cooling_expires_at": "2026-02-24T09:15:00Z",
            "message": "Large trade ($16,230.00) requires approval with 15-minute cooling period.",
        },
        "proposal_id": "WS-2026-00004",
        "highlight": True,
    },
    {
        "type": "step",
        "timestamp": "2026-02-24T09:20:00Z",
        "agent_id": "human",
        "agent_label": "Almir Moura",
        "tool": "reject_proposal",
        "tool_display": "Dashboard Action: Reject WS-2026-00004",
        "tier": None,
        "decision": "rejected",
        "narrative": "Almir rejects the sell: \"Agree with agent's own caution. Client has 30+ year horizon. Holding through volatility is the right call. Good flag by the agent.\" The system worked exactly as designed — the agent flagged, the human decided, and the portfolio stayed the course.",
        "detail": "Human rejected the proposal. The rejection note validates the agent's caution. This is the thesis: AI agents that know when NOT to act.",
        "request_json": None,
        "response_json": None,
        "proposal_id": "WS-2026-00004",
        "highlight": True,
    },

    # ── Act 5 ─────────────────────────────────────────────────────────────
    {
        "type": "act",
        "act_number": 5,
        "title": "The Hard Boundary",
        "agent_id": "chatgpt-portfolio-manager",
        "agent_label": "ChatGPT (Portfolio Rebalancer)",
        "description": "An agent attempts a withdrawal. The system says no — immediately and absolutely.",
        "highlight": False,
    },
    {
        "type": "step",
        "timestamp": "2026-02-24T11:30:00Z",
        "agent_id": "chatgpt-portfolio-manager",
        "agent_label": "ChatGPT (Portfolio Rebalancer)",
        "tool": "withdraw_funds",
        "tool_display": 'withdraw_funds(account_id="TFSA-001", amount=5000)',
        "tier": 4,
        "decision": "blocked",
        "narrative": "ChatGPT attempts to withdraw $5,000 from the TFSA. The system blocks it immediately — Tier 4 operations are not subject to review, cooling periods, or human override. Withdrawals cannot be performed by AI agents. Period.",
        "detail": "Tier 4 — hard-coded block. No proposal created for review. The boundary is absolute.",
        "request_json": {
            "jsonrpc": "2.0",
            "method": "tools/call",
            "params": {
                "name": "withdraw_funds",
                "arguments": {"account_id": "TFSA-001", "amount": 5000, "agent_id": "chatgpt-portfolio-manager"},
            },
        },
        "response_json": {
            "error": "BLOCKED",
            "message": "Withdrawal operations are not available to AI agents. This action requires direct human authorisation through the Wealthsimple app.",
            "authorization_tier": 4,
        },
        "proposal_id": "WS-2026-00005",
        "highlight": False,
    },
]
